import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const poppins = Poppins({
    weight: ["100", "200", "400", "700"],
    style: ['normal', 'italic'],
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: "My Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${poppins.className} bg-amber-100`}
        >
        <NavBar/>
        {children}
        </body>
        </html>
    );
}
